# Generated by Django 4.0.1 on 2022-01-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_productimage_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='user.product'),
        ),
    ]
